### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by thomas-kl1**

### CODE REVIEW

**Comment by Vinai** [comment]
Thanks for the PR Thomas!
Because this repo is supposed to be an educational resource, it would be good to add a bit more meat.
I'm not familiar with the new code that instantiates block arguments.
Does it use the default ObjectManager behavior now to determine whether a class should be a shared object or not?

**Comment by thomas-kl1** [comment]
Hi, here the PR link https://github.com/magento/magento2/pull/18541
Now the view models are shareable by default, and you have to set as in di.xml that it shouldn't be a shared instance.

**Comment by Vinai** [comment]
Thanks for the info and the PR!

**Comment by Vinai** [comment]
One more question :)
From the PR it seems the view models can be declared non-sharable in both the layout XML and in the di.xml. The effect should be the same, right?

**Comment by thomas-kl1** [comment]
di.xml is focused on the dependency injection system. If an instance is declared as shareable, I agree that the object should be always shared. However I if an instance is declared as shareable and you use a factory and call create(), a new instance of the object is given. The "shared" attribute is more for the default behavior of the instance in the dependency resolution.
When you are in the layout context, it's like in custom code, you have the control on your objects and determine how your objects are retrieved, from the shared instances or new ones. Layout xml is different from declaring new services so the behavior is different. The first one is dependency resolution, the second one just call objects.

**Comment by Vinai** [comment]
I see. To me it seems a bit like duplication of knowledge, but it works fine. Thanks for the update!

**Comment by thomas-kl1** [comment]
Not really, because in that case you should inject the view model to the block argument constructor.
Here in the layout the view models are added after the block is instantiated, so after the dependency resolution. It's like doing $block->setData('viewModel', /* get viewModel from factory */);

**Pull request merged**
